teamslist = [
"Duke", "Ohio St.", "Kansas", "Texas", "Purdue", "Pittsburgh",
"Brigham Young", "Wisconsin", "Kentucky", "Washington",
"San Diego St.", "North Carolina", "Syracuse", "Villanova",
"Arizona", "Louisville", "Georgetown", "Utah St.", "Maryland",
"George Mason", "Cincinnati", "Notre Dame", "Missouri",
"West Virginia", "Illinois", "Connecticut", "Nevada Las Vegas",
"Vanderbilt", "Belmont", "Virginia Tech", "Florida", "St. John's",
"Marquette", "Clemson", "Kansas St.", "Temple", "Alabama", "Xavier",
"Michigan St.", "Duquesne", "Texas A&M", "Minnesota", "St. Mary's",
"Florida St.", "Nebraska", "Tennessee", "New Mexico", "Michigan",
"Southern California", "Gonzaga", "Penn St.", "Wichita St.", "UCLA",
"Washington St.", "Butler", "UAB", "Old Dominion", "Richmond",
"Georgia", "Seton Hall", "Northwestern", "Colorado", "Miami FL",
"Baylor", "Colorado St.", "Southern Mississippi",
"College of Charleston", "Cleveland St.", "Iona", "Indiana",
"California", "Boston College", "Mississippi", "Oakland", "Oregon",
"Texas El Paso", "Marshall", "Iowa St.", "Harvard", "Providence",
"Rutgers", "North Carolina St.", "Missouri St.", "Iowa",
"Central Florida", "Valparaiso", "Oklahoma St.", "Memphis",
"Arkansas", "Long Beach St.", "Fairfield", "Virginia Commonwealth",
"Stanford", "Dayton", "James Madison", "Bucknell", "Drexel",
"South Dakota St.", "Portland", "Princeton", "Coastal Carolina",
"Buffalo", "Tulsa", "Boise St.", "Georgia Tech", "Vermont",
"Wright St.", "Virginia", "Morehead St.", "Montana",
"East Tennessee St.", "Wofford", "Rider", "Pacific", "Akron",
"Northern Colorado", "Rhode Island", "Long Island", "Creighton",
"South Carolina", "Arizona St.", "South Florida", "New Mexico St.",
"Utah", "Northern Iowa", "Idaho", "Texas Tech", "Murray St.",
"Weber St.", "St. Bonaventure", "Kent St.", "Austin Peay",
"Indiana St.", "Oral Roberts", "Air Force", "Oklahoma", "Nevada",
"IUPUI", "UC Santa Barbara", "Mississippi St.", "St. Peter's",
"Northern Arizona", "Santa Clara", "Central Connecticut", "Davidson",
"St. Louis", "Furman", "East Carolina", "Fresno St.", "Rice",
"Wisconsin Milwaukee", "Hofstra", "Detroit", "Massachusetts",
"George Washington", "San Francisco", "Southern Methodist", "Hawaii",
"Lipscomb", "Robert Morris", "Stephen F. Austin", "Cal Poly",
"Jacksonville", "Oregon St.", "Quinnipiac", "Loyola Chicago",
"NC Asheville", "Ball St.", "Wisconsin Green Bay", "Loyola MD",
"Pennsylvania", "Ohio", "Canisius", "Boston University", "DePaul",
"Tulane", "San Jose St.", "IUPU Fort Wayne", "Texas Christian",
"North Dakota St.", "American", "Western Carolina", "Yale", "Denver",
"Florida Atlantic", "Miami OH", "Siena", "Drake", "Delaware",
"Nicholls St.", "Houston", "Maine", "La Salle", "Evansville",
"Charlotte", "Arkansas St.", "Lehigh", "Western Michigan",
"Northeastern", "Cornell", "Middle Tennessee", "Western Kentucky",
"NC Wilmington", "McNeese St.", "Louisiana St.", "Wyoming",
"Virginia Military Inst", "Eastern Kentucky", "Sam Houston St.",
"William & Mary", "North Texas", "Mercer", "Saint Joseph's",
"Liberty", "Louisiana Tech", "Tennessee St.", "Charleston Southern",
"Loyola Marymount", "Lamar", "UC Irvine", "Arkansas Little Rock",
"Pepperdine", "Winthrop", "Bradley", "Tennessee Tech", "Holy Cross",
"Texas Arlington", "Texas St.", "St. Francis NY", "Columbia",
"Appalachian St.", "Georgia St.", "Wagner", "North Florida",
"UC Davis", "Lafayette", "Auburn", "Hampton", "Louisiana Lafayette",
"Brown", "Texas San Antonio", "Cal St. Northridge",
"Southern Illinois", "Illinois St.", "Albany", "Elon", "Wake Forest",
"Utah Valley", "Missouri Kansas City", "Morgan St.",
"Youngstown St.", "Southern Utah", "Campbell", "Coppin St.",
"Cal St. Fullerton", "Presbyterian", "Eastern Michigan",
"Illinois Chicago", "Texas Southern", "Bowling Green",
"Sacred Heart", "Stony Brook", "Mount St. Mary's", "Troy",
"Southeastern Louisiana", "Northwestern St.", "Montana St.",
"Portland St.", "Florida International", "Seattle", "Fordham",
"Northern Illinois", "Towson", "Monmouth", "Jackson St.",
"Central Michigan", "Navy", "Savannah St.", "Army", "Chattanooga",
"St. Francis PA", "Jacksonville St.", "Eastern Washington",
"The Citadel", "NC Greensboro", "Bethune Cookman",
"North Carolina A&T", "Gardner Webb", "South Alabama",
"New Hampshire", "UC Riverside", "San Diego", "Niagara",
"Florida Gulf Coast", "South Dakota", "Southeast Missouri St.",
"Tennessee Martin", "Delaware St.", "Idaho St.",
"Cal St. Bakersfield", "North Dakota", "Norfolk St.", "Hartford",
"Eastern Illinois", "Mississippi Valley St.", "Manhattan", "Stetson",
"North Carolina Central", "Alabama A&M", "High Point", "Samford",
"Colgate", "Bryant", "NJ Inst of Technology", "Kennesaw St.",
"Sacramento St.", "Binghamton", "Marist", "Longwood", "Dartmouth",
"Texas A&M Corpus Chris", "South Carolina Upstate",
"Louisiana Monroe", "Georgia Southern", "Florida A&M",
"Fairleigh Dickinson", "Alabama St.", "Western Illinois",
"South Carolina St.", "Radford", "Toledo", "Texas Pan American",
"MD Baltimore County", "Central Arkansas", "Arkansas Pine Bluff",
"Houston Baptist", "Howard", "Maryland Eastern Shore", "Grambling",
"Prairie View A&M", "Alcorn St.", "SIU Edwardsville", "Chicago St.",
"Southern"]
